apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REGION_NAME
              value: us-east-2
            - name: ENVIRONMENT_NAME
              value: dev
            - name: SERVER_PORT
              value: !!str {{ .Values.config.serverPort }}
            - name: SLACK_ADMIN_CHANNEL_ID
              value: !!str {{ .Values.config.slackAdminChannelId }}
            - name: SLACK_DEFAULT_CHANNEL_ID
              value: !!str {{ .Values.config.slackDefaultChannelId }}
            - name: SLACK_BOT_TOKEN
              value: !!str {{ .Values.config.slackBotToken }}
            - name: SLACK_APP_TOKEN
              value: !!str {{ .Values.config.slackAppToken }}
          ports:
            - containerPort: {{ .Values.config.serverPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.config.serverPort }}
            periodSeconds: 5
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.config.serverPort }}
            periodSeconds: 30
            timeoutSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
