apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.config.serverPort }}
      targetPort: {{ .Values.config.serverPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
